import type { KnowledgeDomain } from "./types";

export const KNOWLEDGE_BASE: KnowledgeDomain[] = [
  {
    id: "cmmc-l2",
    topic: "cmmc-l2",
    lastUpdated: "2026-04-20",
    facts: [
      {
        claim: "CMMC Level 2 requires all 110 NIST SP 800-171 Rev 2 controls.",
        evidence: "DoD CMMC 2.0 final rule, 32 CFR Part 170 (December 2024)",
        confidence: "high",
        source: "https://www.acq.osd.mil/cmmc/",
        tags: ["cmmc", "nist", "controls", "level-2"],
      },
      {
        claim: "CMMC Level 2 enforcement begins November 2026 for all DoD prime contractors.",
        evidence: "DFARS clause 252.204-7021 phased enforcement schedule",
        confidence: "high",
        source: "https://www.federalregister.gov/documents/2024/12/26/2024-29439",
        tags: ["cmmc", "deadline", "enforcement", "dfars"],
      },
      {
        claim: "SPRS scores range from -203 (all controls failed) to +110 (all controls met).",
        evidence: "DoD SPRS scoring methodology v1.2.1",
        confidence: "high",
        source: "https://www.sprs.csd.disa.mil/",
        tags: ["sprs", "scoring", "nist", "cmmc"],
      },
      {
        claim: "C3PAO assessments cost $30K–$150K depending on contractor size.",
        evidence: "Industry survey of 47 C3PAOs, 2025",
        confidence: "medium",
        source: "https://cybermaturityalliance.org/",
        tags: ["c3pao", "cost", "assessment", "cmmc"],
      },
      {
        claim: "Cloud-based DLP that sends prompts to a third-party service violates CMMC AC.L2-3.1.3 (CUI flow control).",
        evidence: "NIST SP 800-171 Rev 2 AC.3.014, CMMC AC.L2-3.1.3 control description",
        confidence: "high",
        source: "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-171r2.pdf",
        tags: ["cmmc", "cui", "dlp", "local-only", "architecture"],
      },
      {
        claim: "Approximately 80,000 US defense contractors must achieve CMMC Level 2.",
        evidence: "DoD industrial base size estimates, 2024 CMMC rule preamble",
        confidence: "medium",
        source: "https://www.acq.osd.mil/cmmc/",
        tags: ["market", "cmmc", "contractors", "tam"],
      },
      {
        claim: "Less than 0.5% of defense contractors are currently CMMC certified.",
        evidence: "C3PAO capacity analysis, Cyber AB marketplace data, April 2026",
        confidence: "medium",
        source: "https://cyberab.org/",
        tags: ["market", "cmmc", "certification", "gap"],
      },
    ],
  },
  {
    id: "hipaa",
    topic: "hipaa",
    lastUpdated: "2026-04-20",
    facts: [
      {
        claim: "HIPAA Safe Harbor requires removing all 18 PHI identifiers before data is considered de-identified.",
        evidence: "45 CFR 164.514(b)(2) — Safe Harbor method",
        confidence: "high",
        source: "https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/index.html",
        tags: ["hipaa", "phi", "de-identification", "safe-harbor"],
      },
      {
        claim: "The 18 PHI identifiers include: names, geographic subdivisions below state, dates (except year), phone numbers, fax numbers, email addresses, SSNs, MRNs, health plan beneficiary numbers, account numbers, certificate/license numbers, VINs, device identifiers, URLs, IPs, biometric identifiers, full-face photos, and any other unique identifying number.",
        evidence: "45 CFR 164.514(b)(2)(i)",
        confidence: "high",
        source: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E/section-164.514",
        tags: ["hipaa", "phi", "identifiers"],
      },
      {
        claim: "HIPAA Breach Rule requires notification within 60 days of discovering a breach affecting 500+ individuals.",
        evidence: "45 CFR 164.408 — Notification to HHS",
        confidence: "high",
        source: "https://www.hhs.gov/hipaa/for-professionals/breach-notification/index.html",
        tags: ["hipaa", "breach", "notification", "timeline"],
      },
    ],
  },
  {
    id: "soc2",
    topic: "soc2",
    lastUpdated: "2026-04-20",
    facts: [
      {
        claim: "SOC 2 Type II covers 5 Trust Service Criteria: Security, Availability, Processing Integrity, Confidentiality, Confidential Privacy.",
        evidence: "AICPA TSC 2017 with 2022 points of focus",
        confidence: "high",
        source: "https://www.aicpa-cima.com/resources/landing/system-and-organization-controls-soc-suite-of-services",
        tags: ["soc2", "tsc", "type-ii", "aicpa"],
      },
      {
        claim: "SOC 2 Type II audit period is typically 6–12 months; Type I is a point-in-time snapshot.",
        evidence: "AICPA SOC 2 guide",
        confidence: "high",
        source: "https://www.aicpa-cima.com/",
        tags: ["soc2", "audit", "type-i", "type-ii"],
      },
      {
        claim: "SOC 2 CC6.1 requires logical and physical access controls — AI prompt logging satisfies evidence requirements.",
        evidence: "AICPA TSC 2017 CC6.1 common criteria",
        confidence: "medium",
        source: "https://www.aicpa-cima.com/",
        tags: ["soc2", "cc6", "access-control", "audit-trail"],
      },
    ],
  },
  {
    id: "competitors",
    topic: "competitors",
    lastUpdated: "2026-04-25",
    facts: [
      {
        claim: "Nightfall AI is cloud-based — all scanned data passes through Nightfall's servers, disqualifying it for CMMC CUI environments under DFARS 7012.",
        evidence: "Nightfall architecture docs, privacy policy; DFARS 7012 CUI protection requirements",
        confidence: "high",
        source: "https://nightfall.ai/",
        tags: ["competitor", "nightfall", "cloud", "cmmc", "disqualified", "dfars"],
      },
      {
        claim: "Strac has MCP DLP integration (first mover) but is cloud-based with no on-premise option — disqualified for CMMC CUI scanning.",
        evidence: "Strac product docs, April 2026; MCP DLP announcement",
        confidence: "high",
        source: "https://www.strac.io/",
        tags: ["competitor", "strac", "mcp", "cloud", "cmmc", "disqualified"],
      },
      {
        claim: "Microsoft Purview requires Azure AD and Microsoft 365 — incompatible with non-Microsoft AI tooling (OpenAI API, Claude direct). GCC High variant does not cover AI prompt scanning.",
        evidence: "Purview DLP documentation — scope limited to M365 workloads; GCC High boundary definition",
        confidence: "high",
        source: "https://learn.microsoft.com/en-us/purview/dlp-learn-about-dlp",
        tags: ["competitor", "purview", "microsoft", "azure", "scope-limited", "gcc"],
      },
      {
        claim: "Cyberhaven uses an endpoint agent that sends behavioral analytics to a cloud backend — the analytics data is not CUI but the architecture requires trusting a third party with metadata.",
        evidence: "Cyberhaven architecture docs, April 2026",
        confidence: "medium",
        source: "https://www.cyberhaven.com/",
        tags: ["competitor", "cyberhaven", "endpoint", "cloud", "analytics"],
      },
      {
        claim: "Symantec (Broadcom) DLP has an on-premise option but requires a six-month enterprise deployment at $$$$$. No AI-specific patterns for ChatGPT or Copilot. Target customer: Fortune 500, not SMB defense contractors.",
        evidence: "Symantec DLP pricing and deployment guide, 2025",
        confidence: "high",
        source: "https://www.broadcom.com/products/cybersecurity/information-protection/data-loss-prevention",
        tags: ["competitor", "symantec", "broadcom", "on-premise", "enterprise", "legacy"],
      },
      {
        claim: "Netskope uses a TLS-breaking cloud proxy architecture — CUI passes through Netskope's cloud infrastructure, violating DFARS 7012 local processing requirements.",
        evidence: "Netskope architecture whitepaper; DFARS 7012 CUI boundary requirements",
        confidence: "high",
        source: "https://www.netskope.com/",
        tags: ["competitor", "netskope", "proxy", "cloud", "tls", "dfars", "disqualified"],
      },
      {
        claim: "No competitor offers simultaneous CMMC + HIPAA + SOC 2 enforcement in a single local proxy deployable in under 10 minutes.",
        evidence: "Competitive audit of Nightfall, Strac, Purview, Cyberhaven, Netskope, Symantec, Forcepoint, Zscaler — April 2026",
        confidence: "high",
        source: "internal",
        tags: ["competitor", "differentiation", "local-only", "multi-framework", "deployment"],
      },
      {
        claim: "The core sales sentence that closes against every competitor: 'Every cloud-based AI DLP tool sends your CUI to their servers to scan it. That is itself a potential CUI spill under DFARS 7012. Hound Shield scans everything locally. Nothing leaves your network.'",
        evidence: "OODA competitive analysis, April 2026; DFARS 7012 CUI protection requirements",
        confidence: "high",
        source: "internal",
        tags: ["competitor", "sales", "positioning", "dfars", "local-only", "moat"],
      },
    ],
  },
  {
    id: "product-roadmap",
    topic: "product-roadmap",
    lastUpdated: "2026-04-30",
    facts: [
      {
        claim: "Shannon entropy engine (H > 3.5 threshold) planned to detect API keys, JWTs, and secrets with no known regex pattern — complements the 16-pattern CUI scanner.",
        evidence: "OODA product roadmap, April 2026; information-theoretic secret detection",
        confidence: "high",
        source: "internal",
        tags: ["entropy", "shannon", "api-key", "secret", "scanner", "roadmap"],
      },
      {
        claim: "Browser extension (Chrome/Edge) planned for paste interception at the UI layer — intercepts clipboard events on AI chat sites, runs 16-pattern WASM scanner, safe-redacts CUI before paste completes.",
        evidence: "OODA product roadmap, April 2026",
        confidence: "high",
        source: "internal",
        tags: ["extension", "chrome", "edge", "paste", "wasm", "redact", "byod", "roadmap"],
      },
      {
        claim: "Extended AI provider support planned: Perplexity, Grok, Mistral, Meta AI (Llama.ai) added as recognized proxy targets. Current coverage: ChatGPT, Copilot, Claude, OpenAI API.",
        evidence: "OODA product roadmap, April 2026",
        confidence: "high",
        source: "internal",
        tags: ["perplexity", "grok", "mistral", "meta", "providers", "roadmap"],
      },
      {
        claim: "Sprint 1 MVP goal: Jordan deploys HoundShield in under 10 minutes and exports a C3PAO-ready PDF audit report (event log + NIST control mapping + SPRS improvement estimate).",
        evidence: "Sprint 1 definition, CLAUDE.md, April 2026",
        confidence: "high",
        source: "internal",
        tags: ["jordan", "sprint", "mvp", "docker", "pdf", "c3pao", "10-minutes"],
      },
      {
        claim: "OODA BUILD verdict (April 2026): Paul Graham would fund HoundShield. CMMC enforcement is a federal law (DFARS 7012), not a preference. Local-only architecture moat cannot be copied without rebuilding competitors' cloud stacks.",
        evidence: "OODA Phase 1-5 analysis, April 2026",
        confidence: "high",
        source: "internal",
        tags: ["ooda", "paul-graham", "verdict", "build", "dfars", "moat", "yc"],
      },
    ],
  },
  {
    id: "architecture",
    topic: "architecture",
    lastUpdated: "2026-04-30",
    facts: [
      {
        claim: "Proxy (network layer) and browser extension (UI layer) are complementary deployment paths. Proxy requires IT network config change. Extension requires zero IT involvement — suitable for BYOD and home office.",
        evidence: "HoundShield architecture design, April 2026",
        confidence: "high",
        source: "internal",
        tags: ["proxy", "extension", "architecture", "byod", "deployment", "layer"],
      },
      {
        claim: "Local-only data boundary is sacred: all AI prompt content, CUI detection results, audit logs stay on customer infrastructure. Only license key hash and prompt count (a number, not content) leave the network.",
        evidence: "DFARS 7012 requirement; HoundShield architecture constraint",
        confidence: "high",
        source: "internal",
        tags: ["local-only", "data-boundary", "dfars", "cui", "prompt", "constraint", "sacred"],
      },
    ],
  },
  {
    id: "market",
    topic: "market",
    lastUpdated: "2026-04-25",
    facts: [
      {
        claim: "The CMMC compliance market TAM is estimated at $4–8B annually including assessments, tooling, and remediation.",
        evidence: "MarketsandMarkets cybersecurity compliance market report, 2025",
        confidence: "low",
        source: "https://www.marketsandmarkets.com/",
        tags: ["market", "tam", "cmmc", "revenue"],
      },
      {
        claim: "ChatGPT, Copilot, and Claude are used by >60% of defense contractor knowledge workers per 2025 workforce survey.",
        evidence: "ISACA State of AI in the Workforce survey, 2025",
        confidence: "medium",
        source: "https://www.isaca.org/",
        tags: ["market", "ai-adoption", "defense", "chatgpt", "copilot"],
      },
      {
        claim: "Primary buyer persona: Jordan — IT Security Manager at a 50-250 person DoD subcontractor. C3PAO pre-assessment booked within 90 days. Engineers use ChatGPT and Copilot daily. No visibility into what they are sending. C3PAO questionnaire asks: 'What AI tool controls do you have?' Jordan cannot answer.",
        evidence: "OODA customer discovery framework, April 2026",
        confidence: "high",
        source: "internal",
        tags: ["market", "persona", "jordan", "buyer", "cmmc", "c3pao"],
      },
      {
        claim: "C3PAO distribution channel: each C3PAO has 20-100 defense contractor clients actively seeking compliance tools. One C3PAO conversation equals 10-50 potential customers. Find at: marketplace.cmmcab.org/s/find-a-c3pao",
        evidence: "CMMC-AB marketplace data; channel analysis April 2026",
        confidence: "high",
        source: "https://marketplace.cmmcab.org/",
        tags: ["market", "c3pao", "channel", "distribution", "sales"],
      },
      {
        claim: "Current workarounds defense contractors use instead of a real solution: (1) do nothing and hope, (2) block ChatGPT at DNS level (bypassed by mobile/VPN), (3) write a policy document claiming it as a control (C3PAOs now reject this as insufficient evidence).",
        evidence: "Customer discovery interviews; C3PAO feedback on AI controls evidence, 2026",
        confidence: "high",
        source: "internal",
        tags: ["market", "workaround", "behavior", "dns", "policy", "inertia"],
      },
      {
        claim: "OODA verdict: BUILD. The local-only architecture moat is real. The forcing function (CMMC enforcement November 2026) is credible. The beachhead (50-250 person DoD contractors) is accessible via C3PAO channel. Paul Graham would fund this in its current form.",
        evidence: "OODA Phase 1-5 analysis, April 2026",
        confidence: "high",
        source: "internal",
        tags: ["market", "ooda", "verdict", "build", "yc", "strategy"],
      },
    ],
  },
];
