/**
 * Demo data for when Supabase isn't configured.
 * Shows realistic compliance events so buyers can see the product in action.
 */

const now = Date.now();
const hour = 3600000;

export const DEMO_EVENTS = [
  {
    id: "demo-001",
    created_at: new Date(now - 0.5 * hour).toISOString(),
    user_id: "eng-team@acme.co",
    prompt_hash: "a1b2c3d4e5f6",
    destination_provider: "OpenAI",
    risk_level: "CRITICAL",
    classifications: ["PII", "FINANCIAL"],
    action_taken: "BLOCKED",
    confidence_score: 0.97,
    detected_entities: [
      { type: "SSN", value_redacted: "***-**-4832", pattern_matched: "ssn_regex", confidence: 0.98 },
      { type: "CREDIT_CARD", value_redacted: "****-****-****-7291", pattern_matched: "cc_regex", confidence: 0.96 },
    ],
    processing_time_ms: 12,
    seed_hash: null,
  },
  {
    id: "demo-002",
    created_at: new Date(now - 1.2 * hour).toISOString(),
    user_id: "data-science@acme.co",
    prompt_hash: "b2c3d4e5f6a1",
    destination_provider: "Anthropic",
    risk_level: "HIGH",
    classifications: ["STRATEGIC"],
    action_taken: "QUARANTINED",
    confidence_score: 0.89,
    detected_entities: [
      { type: "M&A_DATA", value_redacted: "[ACQUISITION DETAILS REDACTED]", pattern_matched: "ma_regex", confidence: 0.89 },
    ],
    processing_time_ms: 18,
    seed_hash: null,
  },
  {
    id: "demo-003",
    created_at: new Date(now - 2.1 * hour).toISOString(),
    user_id: "marketing@acme.co",
    prompt_hash: "c3d4e5f6a1b2",
    destination_provider: "OpenAI",
    risk_level: "MEDIUM",
    classifications: ["PII"],
    action_taken: "QUARANTINED",
    confidence_score: 0.75,
    detected_entities: [
      { type: "EMAIL", value_redacted: "j***@acme.co", pattern_matched: "email_regex", confidence: 0.95 },
      { type: "PHONE", value_redacted: "(***) ***-8834", pattern_matched: "phone_regex", confidence: 0.72 },
    ],
    processing_time_ms: 8,
    seed_hash: null,
  },
  {
    id: "demo-004",
    created_at: new Date(now - 3.5 * hour).toISOString(),
    user_id: "eng-team@acme.co",
    prompt_hash: "d4e5f6a1b2c3",
    destination_provider: "Google",
    risk_level: "LOW",
    classifications: [],
    action_taken: "ALLOWED",
    confidence_score: 0.15,
    detected_entities: [],
    processing_time_ms: 4,
    seed_hash: null,
  },
  {
    id: "demo-005",
    created_at: new Date(now - 4.0 * hour).toISOString(),
    user_id: "devops@acme.co",
    prompt_hash: "e5f6a1b2c3d4",
    destination_provider: "OpenAI",
    risk_level: "CRITICAL",
    classifications: ["IP"],
    action_taken: "BLOCKED",
    confidence_score: 0.99,
    detected_entities: [
      { type: "API_KEY", value_redacted: "sk-****...****", pattern_matched: "api_key_regex", confidence: 0.99 },
      { type: "AWS_CREDENTIALS", value_redacted: "AKIA****...****", pattern_matched: "aws_regex", confidence: 0.97 },
    ],
    processing_time_ms: 6,
    seed_hash: null,
  },
  {
    id: "demo-006",
    created_at: new Date(now - 5.5 * hour).toISOString(),
    user_id: "product@acme.co",
    prompt_hash: "f6a1b2c3d4e5",
    destination_provider: "Anthropic",
    risk_level: "NONE",
    classifications: [],
    action_taken: "ALLOWED",
    confidence_score: 0.02,
    detected_entities: [],
    processing_time_ms: 3,
    seed_hash: null,
  },
  {
    id: "demo-007",
    created_at: new Date(now - 6.0 * hour).toISOString(),
    user_id: "finance@acme.co",
    prompt_hash: "a7b8c9d0e1f2",
    destination_provider: "OpenAI",
    risk_level: "HIGH",
    classifications: ["FINANCIAL"],
    action_taken: "BLOCKED",
    confidence_score: 0.92,
    detected_entities: [
      { type: "REVENUE_DATA", value_redacted: "[REVENUE FIGURES REDACTED]", pattern_matched: "revenue_regex", confidence: 0.92 },
      { type: "ROUTING_NUMBER", value_redacted: "****5678", pattern_matched: "routing_regex", confidence: 0.88 },
    ],
    processing_time_ms: 14,
    seed_hash: null,
  },
  {
    id: "demo-008",
    created_at: new Date(now - 7.5 * hour).toISOString(),
    user_id: "eng-team@acme.co",
    prompt_hash: "b8c9d0e1f2a3",
    destination_provider: "Google",
    risk_level: "LOW",
    classifications: [],
    action_taken: "ALLOWED",
    confidence_score: 0.08,
    detected_entities: [],
    processing_time_ms: 5,
    seed_hash: null,
  },
  {
    id: "demo-009",
    created_at: new Date(now - 9.0 * hour).toISOString(),
    user_id: "hr@acme.co",
    prompt_hash: "c9d0e1f2a3b4",
    destination_provider: "OpenAI",
    risk_level: "HIGH",
    classifications: ["PII"],
    action_taken: "QUARANTINED",
    confidence_score: 0.85,
    detected_entities: [
      { type: "DOB", value_redacted: "**/**/1989", pattern_matched: "dob_regex", confidence: 0.85 },
      { type: "SSN", value_redacted: "***-**-1234", pattern_matched: "ssn_regex", confidence: 0.91 },
    ],
    processing_time_ms: 11,
    seed_hash: null,
  },
  {
    id: "demo-010",
    created_at: new Date(now - 11.0 * hour).toISOString(),
    user_id: "cto@acme.co",
    prompt_hash: "d0e1f2a3b4c5",
    destination_provider: "Anthropic",
    risk_level: "MEDIUM",
    classifications: ["STRATEGIC"],
    action_taken: "QUARANTINED",
    confidence_score: 0.72,
    detected_entities: [
      { type: "ROADMAP_DATA", value_redacted: "[PRODUCT ROADMAP REDACTED]", pattern_matched: "roadmap_regex", confidence: 0.72 },
    ],
    processing_time_ms: 9,
    seed_hash: null,
  },
];

export const DEMO_QUARANTINE_ITEMS = [
  {
    id: "q-demo-001",
    created_at: new Date(now - 1.2 * hour).toISOString(),
    review_status: "PENDING",
    priority: 3,
    detected_entities: DEMO_EVENTS[1].detected_entities,
    compliance_events: {
      user_id: "data-science@acme.co",
      risk_level: "HIGH",
      destination_provider: "Anthropic",
    },
  },
  {
    id: "q-demo-002",
    created_at: new Date(now - 2.1 * hour).toISOString(),
    review_status: "PENDING",
    priority: 2,
    detected_entities: DEMO_EVENTS[2].detected_entities,
    compliance_events: {
      user_id: "marketing@acme.co",
      risk_level: "MEDIUM",
      destination_provider: "OpenAI",
    },
  },
  {
    id: "q-demo-003",
    created_at: new Date(now - 9.0 * hour).toISOString(),
    review_status: "PENDING",
    priority: 3,
    detected_entities: DEMO_EVENTS[8].detected_entities,
    compliance_events: {
      user_id: "hr@acme.co",
      risk_level: "HIGH",
      destination_provider: "OpenAI",
    },
  },
  {
    id: "q-demo-004",
    created_at: new Date(now - 11.0 * hour).toISOString(),
    review_status: "PENDING",
    priority: 2,
    detected_entities: DEMO_EVENTS[9].detected_entities,
    compliance_events: {
      user_id: "cto@acme.co",
      risk_level: "MEDIUM",
      destination_provider: "Anthropic",
    },
  },
];
